# Usa una imagen base de Node.js con el gestor de paquetes npm
FROM node:alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json e instala las dependencias
COPY package.json .
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Compila la aplicación para producción
RUN npm run build

# Instala serve para servir la aplicación estática
RUN npm install -g serve

# Expone el puerto en el que la aplicación corre
EXPOSE 3000

# Define el comando para ejecutar la aplicación
CMD ["serve", "-s", "build", "-l", "8080"]
